apiVersion: apps/v1
kind: Deployment
metadata:
  name: translate-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translate-tool
  template:
    metadata:
      labels:
        app: translate-tool
    spec:
      containers:
        - name: translate-tool
          image: eu.gcr.io/paywerk-dev/translate-tool:$GITHUB_SHA
          imagePullPolicy: Always
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
kind: Service
apiVersion: v1
metadata:
  name: translate-tool
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: translate-tool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80