name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm ci
      - run: npm run build
      - name: Unit tests
        run: npm test
      - name: E2E tests
        run: e2e/run.sh
        env:
          PROJECT_GITHUB: ${{secrets.PROJECT_GITHUB}}